server:
  port: 8090

spring:
  application:
    name: category-service
  datasource:
    driver-className: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade-category
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
