server:
  port: 8079
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**

        - id: productModule
          uri: lb://product-service
          predicates:
            - Path=/api/v1/**

        - id: categoryModule
          uri: lb://category-service
          predicates:
            - Path=/api/v1/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/